site_name: РОССЕТИ АСТУ
site_url: https://rosseti-astu-preparator.github.io/

nav:
  - Начало работы:
      - Подключение к Системе: Начало работы/Вход в систему.md
      - Функциональность пользовательской БД: Начало работы/Пользовательская БД.md
      - Общие функции разделов: Начало работы/Общие функции разделов.md

  - Коллекции:
      - Коллекции: Коллекции/Коллекции.md
      - Импорт файлов: Коллекции/Импорт файлов.md
      - Экспорт файлов: Коллекции/Экспорт файлов.md

  - Настройка:
      - Создание настройки: 4_Настройка/4_1_Создание настройки/Создание настройки.md
      - Преобразование данных:
          - Агрегация: 4_Настройка/Преобразование данных/Агрегация.md
          - Проекция: 4_Настройка/Преобразование данных/Проекция.md
          - Соединить: 4_Настройка/Преобразование данных/Соединить.md
          - Объединить: 4_Настройка/Преобразование данных/Объединить.md
          - Преобразование при помощи шаблона: 4_Настройка/Преобразование данных/Преобразование при помощи шаблона.md
          - Таблица коллекции: 4_Настройка/Преобразование данных/Таблица данных.md
      - Редактирование настройки: 4_Настройка/4_2_Редактирование настройки/Редактирование настройки.md
      - Персистирование: 4_Настройка/4_4_Персистирование/Персистирование.md
      - Проверка фиксации изменений: 4_Настройка/4_5_Проверка фиксации изменений/Проверка фиксации изменений.md

  - Процессы: 5_Процессы/Процессы.md

  - Шаблоны:
      - Создание шаблона: 6_Шаблоны/Создание нового шаблона.md
      - Параметр по типу "Источник": 6_Шаблоны/Параметр по типу Источник.md

  - Цепочки:
      - Цепочки преобразований: 7_Цепочки преобразований/Цепочки преобразований.md
      - Программные обработчики: 7_Цепочки преобразований/Программные обработчики.md

  - Файлы: Файлы/Файлы.md

#theme:
#  name: material
#  custom_dir: custom_dir  # директория
#extra_css:
#  - style.css  # имя файла
theme:
  name: mkdocs
  locale: ru


extra_css:
  - extra.css

