site_name: РОССЕТИ АСТУ
site_url: https://rosseti-astu-preparator.github.io/

nav:
  - Начало работы:
      - Подключение к системе: Начало работы/Подключение к системе.md
      - Функциональность пользовательской БД: Начало работы/Пользовательская БД.md

  - Общие функции разделов: Общие функции разделов/Общие функции разделов.md

  - Коллекции:
      - Коллекции: Коллекции/Коллекции.md
      - Импорт файлов: Коллекции/Импорт файлов.md
      - Экспорт файлов: Коллекции/Экспорт файлов.md

  - Настройка:
      - Создание настройки: Настройка/Создание настройки.md
      - Преобразование данных:
          - Агрегация: Настройка/Преобразование данных/Агрегация.md
          - Проекция: Настройка/Преобразование данных/Проекция.md
          - Соединить: Настройка/Преобразование данных/Соединить.md
          - Объединить: Настройка/Преобразование данных/Объединить.md
          - Преобразование при помощи шаблона: Настройка/Преобразование данных/Преобразование при помощи шаблона.md
          - Таблица коллекции: Настройка/Преобразование данных/Таблица данных.md
      - Редактирование настройки: Настройка/Редактирование настройки/Редактирование настройки.md
      - Персистирование: Настройка/Редактирование настройки/Персистирование.md
      - Проверка фиксации изменений: Настройка/Редактирование настройки/Проверка фиксации изменений.md

  - Процессы: Процессы/Процессы.md

  - Шаблоны:
      - Создание шаблона: Шаблоны/Создание нового шаблона.md
      - Параметр по типу "Источник": Шаблоны/Параметр по типу Источник.md

  - Цепочки:
      - Цепочки преобразований: Цепочки преобразований/Цепочки преобразований.md
      - Программные обработчики: Цепочки преобразований/Программные обработчики.md

  - Файлы: Файлы/Файлы.md

theme:
  name: mkdocs
  locale: ru


extra_css:
  - extra.css

